version: '3.8'
services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    command: uvicorn src.fastapi_server:create_app --host 0.0.0.0 --port 8000
  streamlit:
    build: .
    env_file: .env
    environment:
      MCP_API_URL: http://api:8000
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port 8501
    depends_on:
      - api
